title: "Junhao Cai, 蔡俊豪, 채준호"
tab_title: "Homepage"
description: "Focusing on machine unlearning and AI applications. Native-level Chinese and Korean."
url: https://chae-junho.github.io
baseurl: ""
me: "J Cai"
visitor_globe_url: "https://mapmyvisitors.com/globe.js?d=4zSjajbb3_Ic7lmO_NtdPgAowE3L4QJZqk6GfdWOQAI"
google_analytics_id:
google_site_verification:
bing_site_verification:
baidu_site_verification:

author:
  name: "Junhao Cai, 蔡俊豪, 채준호"
  avatar: "images/profile-avatar.jpg"
  bio: "Ph.D. student of CSE, Korea University"
  location: "Seoul, South Korea"
  email: "junhochae@korea.ac.kr"
  googlescholar: "https://scholar.google.com/citations?user=6D4rBUIAAAAJ&hl=en"
  github: chae-junho
  linkedin: junhaocai01
  csdn: "https://blog.csdn.net/cjh0318"
  researchgate:
  uri:
  facebook:
  instagram:
  dblp:
  orcid:
  twitter:
  weibo:
  youtube:

include:
  - _pages
exclude:
  - README.md
  - LICENSE
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor

encoding: utf-8
markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false

defaults:
  - scope:
      path: ""
      type: pages
    values:
      layout: default
      author_profile: true

sass:
  sass_dir: _sass
  style: compressed

timezone: Asia/Seoul

plugins:
  - jekyll-sitemap
  - jekyll-redirect-from

copy_gate:
  salt: "MLXyw24fVlaJtXi0KpDelQ=="
  iterations: 600000
  hash: "LtnRq4vMw/vi5R5yoycmWB2uliqLL+eDLCr9Lg0ttFE="
